debug: false
server:
  port: 9090
  context-path: /services
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
oauth2:
  client-id: travel-api-client
  client-secret: psw
  token-url: http://localhost:8080/oauth/token
  grant-type: client_credentials
mock:
  fareurl: http://localhost:8080/fares/{origin}/{destination}
  searchurl: http://localhost:8080/airports?
  airportsurl: http://localhost:8080/airports
  
